### ISSUE TITLE
Cannot find name 'React'. in `dev`-folder.

### ISSUE THREAD

**Issue by bigmistqke** [solidjs-community/solid-lib-starter#1]
get a `Cannot find name 'React'.`-error in `dev`-folder.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/10504064/214717220-e955cc73-47f6-4ffa-ac99-d55d8e003f86.png">

EDIT: I thought the bug was project-specific, but also happens with fresh `git clone`.

**Comment by thetarnav** [comment]
Thanks, it should be resolved now

**Comment by bigmistqke** [comment]
Yes beautiful, works on my end too.
Thank u!
