### ISSUE TITLE
baseUrl tsconfig not working nicely with tsup/tsup-preset-solid

### ISSUE THREAD

**Issue by bigmistqke** [solidjs-community/solid-lib-starter#3]
A `baseUrl` is defined in the tsconfig, but isn't in `tsup-preset-solid`: this causes an error.

```
// from index.ts
import Example from 'src/Example'

Example // will be typed correctly.
```

But when running `dev`: `Failed to resolve import "src/Example" from "src/index.ts". Does the file exist?`

**Comment by thetarnav** [comment]
when using `tsup-preset-solid` `tsup` options can be overwritten with the `tsupOptions` key. Not sure if there is an option for the base URL specifically though.
```ts
{
  tsupOptions(options) {
    // do whatever to options
    return options;
  },
}
```

**Comment by bigmistqke** [comment]
On further inspection it didn't had anything to do with the `tsup` config, but with `dev/vite.config.ts` instead. 
[Made a PR to add a path-alias](https://github.com/solidjs-community/solid-lib-starter/pull/4)

**Comment by thetarnav** [comment]
it's resolved now I believe
